language: objective-c
osx_image: xcode9.4

notifications:
    slack: cosc345supergroup:SsDTyqgw1oI7wdQnPT0FKIrU
    
branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true #need to clean up project at some stage using swiftlint 
script:
  - set -o pipefail
  - xcodebuild -workspace MPM-Sft-Eng-Proj.xcworkspace -scheme MPM-Sft-Eng-Proj -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

